### ISSUE TITLE
Make player name constant in PlanetWars protocol

### ISSUE THREAD

**Issue by wschella** [ZeusWPI/MOZAIC#114]
Currently we pass the bot's in-game name as it's first parameter (when executing the run command).
I feel like this does not fit nicely in the planned architecture.

We might consider something like in the rules from Googles Planetwars AI Challenge:

> The owner of a planet can be neutral, player 1, or player 2. Players always see themselves as player 1 and their opponents as player 2. The engine works out how to display the world differently to each player. 

Since we don't want to leak information about the number of players, we can modify the protocol to  keep all player names (random) identifiers, except for the player receiving the status, who will be marked as 'Me'.

**Comment by iasoon** [comment]
Can you pinpoint why you think this does not fit nicely in the architecture? I kind of agree, though.
We decided that we don't want numbers because this leaks information about the amount of players in the game (which is unfair to players who only see lower numbers, because they will have less intel). So, implementing this for planetwars would come down to having a fixed 'Me' name. Note that it is also closely related to the name shadowing we wanted to do anyways.

Are there any downsides to this?

**Comment by wschella** [comment]
Agreed that 'me'  is an elegant solution. I feel we might eventually want integers as to improve performance, but that's a different discussion. 

I feel this doesn't fit in the architecture because the gamerules do not control the bot launch process (and they shouldn't), any information given to bots, including their name, should thus be integrated in the communication format.

Possible downside might include gamestates being different for every player, and translation needing to happen on serialization. But that is something we support very well.

**Comment by iasoon** [comment]
Agreed.
I don't think the translation is really an issue, in code nor in performance.
About the integers, I think this is an excellent case of 'premature' (pointless) optimization.

**Comment by iasoon** [comment]
Now that I think of it, this works out nicely for planetwars, but how does this translate to games where the players identifier is relevant to the game, like chess or go?

Do we just assume bots should never need this information?
For chess and go this may not be such a major point, but games exist where players actually take on different roles (e.g. attacker / defender). What is an idiomatic way for this kind of game to communicate this to its players? Extend the protocol with a 'setup message'?

**Comment by wschella** [comment]
@iasoon: A setup message would be an option. But it could be passed in some player-info field each step (roles might change for instance). For example in chess you could denote which player is black and white. I don't think this will prove a major difficulty.

**Comment by iasoon** [comment]
But it does not change in chess.
It would certainly not be a difficulty, but passing a command line argument is not exactly a difficulty either. If we declare one thing as unidiomatic, it might be useful to think about what would be idiomatic instead, is what I am saying.

**Comment by wschella** [comment]
Agreed. The biggest reason for not passing a CL param IMO is the interference in responsibility. Anything _in_ the comm protocol would be idiomatic enough I think. Well, not everything, but you get the point.

**Comment by iasoon** [comment]
Indeed. I think we'd better cut it here as we are moving into yak grounds ;-)

**Comment by wschella** [comment]
Where does that reference come from again?

**Comment by iasoon** [comment]
https://en.m.wiktionary.org/wiki/yak_shaving :-)

**Comment by iasoon** [comment]
So, we discussed we'll implement this by replacing player names by numbers [1..num_players] in the planetwars protocol. In the state for a player, the player numbers will be rotated so that the receiving player will always be player 1.

Importantly, the number 0 is not used, since it is falsy in many languages and could lead to really annoying bugs when writing `if planet.owner` :-)
