### ISSUE TITLE
Follow rules from Google's PlanetWars AI Challenge more closely

### ISSUE THREAD

**Issue by wschella** [ZeusWPI/MOZAIC#115]
Note: this is a discussion, some points might require their own issue.
I've fattened the important parts.

The [rules](https://github.com/aichallenge/aichallenge/wiki/Planet-Wars-Game-Specification).

## Planets

> Planet positions are specified relative to a common origin in Euclidean space. The coordinates are given as **floating point** numbers.

> The **growth rate** of the planet is the number of ships added to the planet after each turn. If the planet is currently owned by neutral, the growth rate is not applied. Only players can get new ships through growth. The growth rate of a planet will never change. It is given as an integer.

## Fleets

> The **total trip length** is given as an integer, representing the total number of turns required to make the trip from source to destination. The turns remaining is also an integer, representing the number of turns left from the current turn to arrive at the destination.

## File Format
Note: this format is also used for gamestate, for which this change might be more relevant.

> The map file format is fairly simple. Each line may be blank, a planet, or a fleet, and each line is separated by Unix style line breaks (LF, not CR or CRLF). **# characters and everything after them are treated as white space (comments)**, so a line beginning with a # character is considered blank, too.

**Comment by iasoon** [comment]
Good thinking, this might be useful.

We already represent planet coordinates as floats, but for some reason you always seem to think we use integers?
Growth rates add an extra dimension to the game. We decided on leaving them out (for now). I don't see an issue with introducing them for the 2nd semester competition, however. This might be a good idea because it makes the game more different from the one we previously played.

About the fleet remark, this looks irrelevant to me since the total trip time can be calculated at any time by the bots.
And as for the file format, I'd argue that staying with json offers more benefits. We could always ignore additional json fields in orders to provide a means to add comments (serde can do this). Alternatively, we could make a dedicated 'comment' field, that gets added to the game logs, which might be very useful in analyzing your bots behaviour when checking out replays.

**Comment by iasoon** [comment]
So, to continue on this: we reflect the rules quite well, we just speak a different protocol. We decided to provide a translator in the client (once the time is right). Can this issue be closed?

**Comment by wschella** [comment]
This is covered mostly by #124 and #116. What remains is whether we want to have different 'growth rates' (in the ouput we could keep it 1 everywhere), but maybe we should have discussion about it.

**Comment by iasoon** [comment]
As we don't have growth rates, I propose the translator adds the 'growth rate: 1' to all planets. That will cause less confusion.

**Comment by iasoon** [comment]
Since we launched the competition, changing the rules won't be the best idea now.
