### ISSUE TITLE
Time out bots

### ISSUE THREAD

**Issue by wschella** [ZeusWPI/MOZAIC#120]
Something something time outs.

Were and how do we want to handle bot-timeouts? What questions do we want/need to ask ourselves? 

Some questions already:
- Is time-outing a bot responsibility of the gameserver, or the gamerules?
  - In case gameserver: how do we propagate these errors to the rules?
  - In case of rules: how do we detect this properly without taking over too much responsibility from the server?
- What metric do we use for detecting time out? Do we support multiple?
- At what point do we take network latency into consideration?
- How would we convey the erroring to the user?
- Add more...

**Comment by iasoon** [comment]
I feel time-outs are entirely the responsibility of the game implementation (see #124). Of course, our utils should support this.

I think for most games, the reasonable way of implementing time-outs is by means of a 'chess clock'. Since most games will have a 'timeout' (literal time in chess or go, #turns in planetwars), this is an useful thing to have for terminating the game. In the case of a turn limit, this can be interpreted as 'you are allowed x time for each turn' - but in a flexible way. This is a good thing, because it allows bots to do for example preprocessing (taking 30 seconds the first turn, but being able to answer in 10ms for all following turns), and it also helps with solving the network delay problem: one random network delay won't cause a time out.

Additionally, this allows limiting how long a game can take, which is nice to have for matchmaking (users often want a quick game to test, not one where their opponent takes 10 minutes for each turn), and for determining 'weight classes' for bots: time limits how many computations they can do.

**Comment by iasoon** [comment]
In the new architecture, this can by having a timer in the game implementation and forcing a step when the timer expires.

**Comment by iasoon** [comment]
I'd say we decided on all questions asked. Tracking implementation in #153 .
