### ISSUE TITLE
The logging problem

### ISSUE THREAD

**Issue by iasoon** [ZeusWPI/MOZAIC#124]
Between the team, there is some discussion about how logging and especially error handling should happen. I suggest we move the discussion here.

## Assumptions

Previously, we made these assumptions:
- MOZAIC is a distributed system.
- Game implementations should receive raw streams from the framework, and be able to take it from there, no assumptions made.

## My proposal

If we want to stay true to these assumptions, I feel the only good way to implement logging and errors is in the following fashion:
- **Game implementations handle all errors**.
  This means nothing happens at the framework-level. Firstly, this does not complicate error handling since all errors are treated equally ('framework-level errors' such as connection issues, and game-specific errors such as failure to comply with the communication protocol). I feel this simplifies both the mental model about MOZAIC, and how you interact with it.
- **Game implementations are responsible for communicating and logging errors**.
  With great responsibility comes great power: this way, you ensure that game implementations have full jurisdiction over their protocol and logging format. You also enable them to make the sensible choice in handling errors, instead of imposing things from the framework-level that might not make sense in your specific game. As a silly example, compare the way an illegal message would be treated in planetwars versus in chess - the error is the same, but the gravity is very different.
- **Bots are responsible for their own logs**.
  When a bot produces for example an illegal message, it would get notified by the game implementation over the game protocol. The bot would then be responsible for logging this error (to, I suggest, its stdout). While this adds some 'complexity' and boilerplate to a bot implementation, it yields two advantages:
  - Errors that occur in the game implementation return to the bot, and will thus be traced in the same stderr log that contains all errors the bot encounters.
  Failure to comply with the protocol is not a problem the game implementation causes, so it should not be burdened with this (note that it is still free to log this in its game log, which it also has full jurisdiction over). This simplifies the implementation of a game, and, in my opinion, better separates responsibility.
  - Moving the responsibility of logging to the bot enables us to log more, such as bot crashes, which would never even reach the game implementation, and thus could not be logged by them. One could of course divide responsibility, but this would not be very friendly to users wishing to debug their bot, since they now have two logs to check.
  - As a small bonus, users have full control over the logging format, which enables them to for example structure their logs in an uniform format to allow machine processing.
- **The client is responsible for capturing bot streams**.
  In order to provide a total log of a bots behaviour, you need its input (stdin), output (stdout), and log (stderr). It would be logical for the program running the bot to capture all these streams, since it is the only program _in the framework_ that has access to all of them. We require the program to be in the framework, since we want to control how the logs get stored. This program would either be the client running on the players computer, or the bot supervisor running on our server (for uploaded bots). This also puts the logs where they would belong, in my opinion.

To summarize: an error occurs in the game implementation, which communicates the error to the bot that caused it, which logs it to its stderr, which gets captured by the client. The error ends up in the bot logs on the users computer.

## Drawbacks

- Bots have to log errors.
  One could argue that any sufficiently advanced bot would want to log information anyways. Having to log errors from the beginning encourages setting this up as soon as possible, and I feel this is something you need anyways to not shoot yourself in the foot.
- The game protocol has to be expanded to contain errors.
  In my opinion, this really sucks. Alas, I also feel the other options suck even more.
  - A separate channel for errors.
    All ways of implementing this are kind of complex (having a separate channel, or multiplexing over one channel), and it does not solve all problems, since sometimes you explicitly want bots to be aware of errors, such as a timeout that happened (due to network delays).
  - Logging errors on the server.
    In addition to the critiques above, a player would not even know an error happened until he checks the logs on the server. This is not intuitive to me.
    Also, this would require either expanding the log format (which sucks even more than expanding the communication protocol imo, since the log format is meant for consumption by visualizers), or having another separate log, with does not exactly simplify things.

**Comment by iasoon** [comment]
Since this is an important issue that will shape our framework, I'd like to hear all your opinions on this! cc @wschella @NoctuaNivalis @tl3ilaxu @timodw

**Comment by NoctuaNivalis** [comment]
I don't know this entire context but:
> Bots are responsible for their own logs.

Sure, but nope. While you can allow a bot to write logs, you shouldn't ask them to. The game should notify a bot about an illegal message, but the game should log this illegal message to the game log directly. A bot *could* log it as well.

**Comment by iasoon** [comment]
@NoctuaNivalis I tend to agree. One of the things we want in MOZAIC is that you can play a match without uploading a bot, by connecting through a TCP connection. We'd probably have a component that wraps the bot and channels its stdin/stdout to the game server, and would also handle matchmaking and these things.

Now, the problem is that due to this, it would be really unergonomic to have errors logged on the server, since you'd want to see them on your machine, as the game is running (the client will often be able to do on-line visualizations, which would miss errors in this case). I'm quite positive errors shouldn't be in the game log either - this is for the state of the game. You could assign a different log, but that doesn't exactly simplify things either.

So, in my opinion error logging/handling should really happen on the client machine. The question then becomes whether the game client or the bot should do it. I am inclined to say the latter, because the other case would require expanding the client from an universal dumb client to a game-specific smart client (since it will have to speak the games error protocol).

**Comment by iasoon** [comment]
Thinking more about this, I feel having a smart client is what we want.

**Comment by wschella** [comment]
Here it goes. 
Note: this is not strictly related to logging only.

## Goals

First some goals I assume we all agree on:
We want to:

- Maximize a game's flexibility: It should be able to take on more responsibility when it means to
- Maximize the frameworks power: We want to make MOZAIC as useful as possible
- Maximize clarity to the user
- Minimize the required game implementation complexity
- Minimize the required bot implementation complexity
- Minimize the frameworks complexity

Of course we can't optimize to all these goals, but we should make a balanced decision.

## My priorities

I believe the most import factor is a minimized bot complexity, followed by clarity for the user.  Next, I feel we should put a baseline for a games flexibility, but shouldn't tunnel-vision on it, as it will rapidly increase a game implementation complexity while decreasing the frameworks power.

Next, I believe we should be able to provide a rudimentary experience with the framework and a minimal game implementation, and that extended functionality should be **opt-in**.

I also believe that in the long run, we can not assume we will be able to keep using a single, non-multiplexed socket, where the only data passing trough it is game-specific.

Things I agree on from the previous proposal:
* Client should capture a bot's streams

Things I don't agree on:
* Bots are responsible for their own errors

Things that change a bit in proposal below:
* Game implementations should handle _all_ errors
* Game implementations should communicate errors

## Proposal

* I think we should define an (albeit very easy) **general framework level protocol** were there is place for **arbitrary game-specific information** we don't understand. The obvious data that would be in there will be game-states and bot commando's. But if a game is not satisfied with the support we provide, they could put anything in there, and create a smart client that handles it well. Eg. error logs

* The **MOZAIC-server**, and **MOZAIC-client** are intermediaries between the game-implementation and the bot that **always understand** the framework protocol.

* The **MOZAIC-server** and **MOZAIC-client** do not understand the arbitrary game information. 

* We make it _possible_ for a game to write a **clients-side implementation** that is smarter than what we could ever provide, this component exists **between** the MOZAIC-client and the bot. Since the game still has an unrestricted information channel at it's disposal, this smart client can provide features we don't support. 

* The server-side game implementation receives from us data-streams we extract from our protocol, same for the client-side implementation.

### Advantages

* We allow the framework to extends it's protocol to support features we (and game-implementators) find convenient. These extensions will act as opt-in utility.** Eg: generic error logs**

* If games are not happy with how we do things, they can still provide it themselves trough their own protocol + smart client. **Eg: specific error handling**

* We allow games to create rudimentary implementations quickly, with a generic implementation for various features. They could extend themselves when the need arrives.

* We can offer very advanced (opt-in) features if the game is willing to structure information in way the framework will understand.

* The games decides whether they use a framework compliant log-format, their own smart-client handles it, or they let the bots handle it themselves.

### Drawbacks

* Designing a flexible framework-level protocol that supports arbitrary data, and opt-in framework functionality might not be an easy task. Note: we don't have to start with something complex.

* Time-outs and measuring ping might be difficult, but it will never be easy imo.

### Argumentation

- I don't we are able to able to avoid using a framework protocol for very long, given their are probably many technical difficulties ahead that we don't see yet, but ultimately won't want to burden a game implementation with.

- I feel like, when we create the socket client-side we are already defining a minimal form of protocol anyway. Since we are deciding how the transfer between stdout to the socket is happening. Eg: if we bind them, a print would equal a socket.send which might not be very efficient in some game protocols, but can't just simply wait for some amount of bytes too. There's polling frequency, etc... So we should either give the bot a socket, or assume we will need a framework protocol from the start.

**Comment by iasoon** [comment]
Reviewing this entire discussion, I feel our viewpoints are more alike than we thought. I'll try to summarize what I think we agree on, taken from the discussion here, on slack, and in person, amended with my own notes.
Please do correct me if I misunderstood any of your poins, or made a logical side-step somewhere!

- Many errors happen on the server that are primarily important to users (e.g. protocol errors). These errors should be propagated to the (client + bot) side.

- We want to put the smallest burden on the player's shoulders. Practically,   this means everything should be done 'for them'. Making them log errors therefore is a bad idea. This puts the burden of logging on behalf of players with the client.

- All communications will have to go over one socket. While two streams could be very ergonomic to develop against, we have mentioned many reasons why this could be bad, some better than others, but I think the main reason is that we lose the main advantage of using TCP sockets: sequentiality. When using two sockets, we have no guarantee that the packets sent over the 'side channel' for turn 1 will arrive before turn 2 has been played, which could lead to awful syncing issues.

- We want a powerful, game-specific client. This allows for a great user experience that doesn't feel clunky due to framework restrictions.
  You mentioned communication between bot and client. I think this is a really powerful idea, that will allow us to have a truly awesome ecosystem with for example interactive debuggers. This could even allow us to do #116 inside the client, which would make us fully compatible without any server effort!  Actually, the way you talk about this concept is really useful: as a component that exists 'between' the client and bot. This is the actual 'game protocol' as we want the user to know it. Similarly, a component exists 'between' the server and client. They speak a different protocol, that should for example carry errors. This is the protocol we are having this dispute over, firstly whether it should exist between client and MOZAIC server, or between server and game implementation (and thus 'bypass' the MOZAIC server). Looking at it this way, I think this is a detail in the greater scheme of things and mostly a pedantic / semantic discussion. I think the right choice will certainly become clear when we develop the project further, and all these concepts in our heads get more real (and more synchronized due to having more anchors, which will also help in not misunderstanding each other like this ;-) ).
  Concluding this section, we will certainly need a client<->server protocol that embeds ('multiplex') what we previously referred to as the 'game protocol'. How this exactly should happen is up for discussion, and in my opinion future work.

- @noctuanivalis is right.
  Up to this point, we have been diluting the meaning of 'logging'. We ment logging as in producing a game log that shows what happened in the game. This is a different meaning from systems logging, which is not meant for replaying, but for keeping an eye on our own system. This should of course happen on the server, not on the client.
  #125 got me to realize that we don't have this and did not think about this yet. When an issue like this happens on the production server, we want to be able to reproduce it. We should think about what "in-house" logs we keep, and how they should look.
  This is not entirely trivial, since logging happens at different 'levels'. The main difficulty here is aggregating all information in an useful format. To elaborate:
  - We have 'raw input' - that what we receive over a socket.
  - We have messages - which we parse from the raw input. We could fail to get a message from the input.
  - We have to check the messages for sensibility - in planet wars, this is checking whether you have enough ships, origin and destination exist, ... . Again, when we have no message, we can not log whether there is a 'logic error'.
  - We have to log what happens as a result of these messages. This is what we currently do in the game log.
  - We have to log what we send to players.
This might seem quite obvious, but what I am trying to get to here is that these things happen in relation to each other, and might be hard to sensibly combine with each other, since things happen at different levels. Remember that timeouts are also a thing, and now imagine how a time-out will look in a raw input stream.
I have not thought about this issue too much yet, but I feel that if we do not approach this right, we might end up with a logging behemoth. I think it would be useful to talk about how we want to handle this for a bit, without trying to decide what should go where, instead sketching a plan to take the bull by the horns.
Another two cents I have to add to this: if we would have an input log and an output log, it would be really trivial to replay all issues that happen. This also doubles as a way of black box testing, since you'd have input and expected output.

**Comment by wschella** [comment]
I agree that we finally seem to be on the same line, which is nice :) Based on what we know now, and what our ideas for the MOZAIC platform are, I also agree with your last comment. So I think it's time we get the this party started again!

PS: About the last statement, for full replay value will probably need an IO log for every 'major component'.

**Comment by iasoon** [comment]
Regarding the new architecture, it makes sense to me to log all client input in the client controllers. The game implementation will then be responsible for the game log.

We probably also want a 'command log' for each bot, that shows all commands that were interpreted by the server, or the errors that occurred trying to interpret them.

Does this cover everything we want to log?

**Comment by wschella** [comment]
We should make sure we are able to also easily debug the game (and it's related components, such as format converter #116 ). I feel like following structure covers everything I can think off:

- Bot: Shouldn't log anything, but can log whatever it wants, taking into consideration that it's stdio streams are captured by the client.
- Client: 
  - Player focused: Logs it's output to the bot (gamestate), and it's input from the bot (commands, debug info, crashes)
  - Game focused: Logs it's output to the server , and it's input from the server
- Server: Logs the 'true' gamestate (not name-shadowed), and _communicates_ errors trying to interpret client output back to the client

**Comment by iasoon** [comment]
While errors certainly should be propagated to the client, don't we want to log them on the server as well? Logging on the client would mean that we, as server operators, have no clue what errors happened, and why they happened.

I think we want to logging in both places, especially since they show something different: the client can log errors that happen inside the bot, but is not aware of network errors. The opposite is true for the client controller.

**Comment by wschella** [comment]
@iasoon My explanation might be incomplete, servers ofcourse still log errors that are not immediately a clients fault. You are correct with the statement that servers should log _as well as_ communicate client interpreting errors. 

About network errors: both the client and the server will have notion about the probable network problems, as they are both connected to it, these are irrelevant details tho. I think we agree. The most important part in my previous post was that clients log their communication to and from the bot in full (possibly together), as well as log their communication to the server in full (possibly together).

**Comment by iasoon** [comment]
Ah, I agree, My post was more targeted at hte server side of things.
So, in conclusion, we log all input, everywere, and we keep a game log.
Does that seem complete to you?

**Comment by wschella** [comment]
Very much :D

**Comment by iasoon** [comment]
side note: this scheme supports replaying in the game server, which can be really useful for debugging.
