### ISSUE TITLE
Non-local networking

### ISSUE THREAD

**Issue by rien** [ZeusWPI/MOZAIC#228]
When we want to play games 'online' we need to be able to make connections trough NAT's. This will require us to implement something like [TCP Hole Punching](https://en.wikipedia.org/wiki/TCP_hole_punching). 

I have found an [interesting Rust library](https://github.com/maidsafe/crust) for P2P connections (which uses this technique). This might be worth looking at.

**Comment by iasoon** [comment]
I am not too sure about all these things, but keep in mind that we don't exactly have a p2p situation, but an actual server with clients. I'm not sure how NAT hole punching will work there. If I understand correctly, the server should first send SYNs to the connecting clients, so that they can then initiate a connection to the server through NAT. This means that we would have to know the client ip's in advance, which we don't. Is that right?

**Comment by iasoon** [comment]
Ah! We should solve this by setting up a MOZAIC proxy server, which is now entirely possible with the new networking code!
I'll create a separate issue.
